// Code generated by qtc from "tempo.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/tempo/tempo.qtpl:1
package tempo

//line app/vtselect/traces/tempo/tempo.qtpl:1
import (
	"sort"
)

//line app/vtselect/traces/tempo/tempo.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/tempo/tempo.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/tempo/tempo.qtpl:7
func StreamSearchTagsResponse(qw422016 *qt422016.Writer, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:7
	qw422016.N().S(`{`)
//line app/vtselect/traces/tempo/tempo.qtpl:10
	sort.Slice(resourceTagList, func(i, j int) bool { return resourceTagList[i] < resourceTagList[j] })
	sort.Slice(spanTagList, func(i, j int) bool { return spanTagList[i] < spanTagList[j] })
	sort.Slice(eventTagList, func(i, j int) bool { return eventTagList[i] < eventTagList[j] })
	sort.Slice(linkTagList, func(i, j int) bool { return linkTagList[i] < linkTagList[j] })
	sort.Slice(instrumentationScopeTagList, func(i, j int) bool { return instrumentationScopeTagList[i] < instrumentationScopeTagList[j] })

//line app/vtselect/traces/tempo/tempo.qtpl:15
	qw422016.N().S(`"scopes":[{"name": "resource","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:20
	if len(resourceTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:21
		qw422016.N().Q(resourceTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:22
		for _, tag := range resourceTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:22
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:23
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:24
		}
//line app/vtselect/traces/tempo/tempo.qtpl:25
	}
//line app/vtselect/traces/tempo/tempo.qtpl:25
	qw422016.N().S(`]},{"name": "span","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:31
	if len(spanTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:33
		qw422016.N().Q(spanTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:34
		for _, tag := range spanTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:34
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:35
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:36
		}
//line app/vtselect/traces/tempo/tempo.qtpl:37
	}
//line app/vtselect/traces/tempo/tempo.qtpl:37
	qw422016.N().S(`]},{"name": "event","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:43
	if len(eventTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:45
		qw422016.N().Q(eventTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:46
		for _, tag := range eventTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:46
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:47
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:48
		}
//line app/vtselect/traces/tempo/tempo.qtpl:49
	}
//line app/vtselect/traces/tempo/tempo.qtpl:49
	qw422016.N().S(`]},{"name": "link","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:55
	if len(linkTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:56
		qw422016.N().Q(linkTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:57
		for _, tag := range linkTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:57
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:58
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:59
		}
//line app/vtselect/traces/tempo/tempo.qtpl:60
	}
//line app/vtselect/traces/tempo/tempo.qtpl:60
	qw422016.N().S(`]},{"name": "instrumentation","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:66
	if len(instrumentationScopeTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:68
		qw422016.N().Q(instrumentationScopeTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:69
		for _, tag := range instrumentationScopeTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:69
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:70
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:71
		}
//line app/vtselect/traces/tempo/tempo.qtpl:72
	}
//line app/vtselect/traces/tempo/tempo.qtpl:72
	qw422016.N().S(`]}],"metrics": {"inspectedBytes": "0"}}`)
//line app/vtselect/traces/tempo/tempo.qtpl:80
}

//line app/vtselect/traces/tempo/tempo.qtpl:80
func WriteSearchTagsResponse(qq422016 qtio422016.Writer, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:80
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:80
	StreamSearchTagsResponse(qw422016, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList)
//line app/vtselect/traces/tempo/tempo.qtpl:80
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:80
}

//line app/vtselect/traces/tempo/tempo.qtpl:80
func SearchTagsResponse(resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) string {
//line app/vtselect/traces/tempo/tempo.qtpl:80
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:80
	WriteSearchTagsResponse(qb422016, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList)
//line app/vtselect/traces/tempo/tempo.qtpl:80
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:80
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:80
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:80
}

//line app/vtselect/traces/tempo/tempo.qtpl:82
func StreamSearchTagValuesResponse(qw422016 *qt422016.Writer, tagValueList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:82
	qw422016.N().S(`{`)
//line app/vtselect/traces/tempo/tempo.qtpl:85
	sort.Slice(tagValueList, func(i, j int) bool { return tagValueList[i] < tagValueList[j] })

//line app/vtselect/traces/tempo/tempo.qtpl:86
	qw422016.N().S(`"tagValues":[`)
//line app/vtselect/traces/tempo/tempo.qtpl:88
	if len(tagValueList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:88
		qw422016.N().S(`{"type": "string","value":`)
//line app/vtselect/traces/tempo/tempo.qtpl:91
		qw422016.N().Q(tagValueList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:91
		qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tempo.qtpl:93
	}
//line app/vtselect/traces/tempo/tempo.qtpl:94
	if len(tagValueList) > 1 {
//line app/vtselect/traces/tempo/tempo.qtpl:95
		for _, tag := range tagValueList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:95
			qw422016.N().S(`,{"type": "string","value":`)
//line app/vtselect/traces/tempo/tempo.qtpl:98
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:98
			qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tempo.qtpl:100
		}
//line app/vtselect/traces/tempo/tempo.qtpl:101
	}
//line app/vtselect/traces/tempo/tempo.qtpl:101
	qw422016.N().S(`],"metrics": {"inspectedBytes": "0"}}`)
//line app/vtselect/traces/tempo/tempo.qtpl:107
}

//line app/vtselect/traces/tempo/tempo.qtpl:107
func WriteSearchTagValuesResponse(qq422016 qtio422016.Writer, tagValueList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:107
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:107
	StreamSearchTagValuesResponse(qw422016, tagValueList)
//line app/vtselect/traces/tempo/tempo.qtpl:107
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:107
}

//line app/vtselect/traces/tempo/tempo.qtpl:107
func SearchTagValuesResponse(tagValueList []string) string {
//line app/vtselect/traces/tempo/tempo.qtpl:107
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:107
	WriteSearchTagValuesResponse(qb422016, tagValueList)
//line app/vtselect/traces/tempo/tempo.qtpl:107
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:107
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:107
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:107
}
